---
- hosts: jenkins
  gather_facts: yes

  vars:
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_password: admin

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins

  tasks:
    - name: make a jenkins job
      jenkins_job:
        config: "{{ lookup('file', 'templates/test.xml') }}"
        name: test
        password: admin
        url: http://localhost:8080
        user: admin
