- hosts: jenkins

  vars:
    jenkins_version: "2.73.1"
    jenkins_url: http://10.10.10.10
    jenkins_port: 80
    jenkins_install_via: "apt"
    jenkins_include_secrets: true
    jenkins_include_custom_files: true
    jenkins_custom_plugins:
        - "openstack-cloud-plugin/openstack-cloud.jpi"

  roles:
    - emmetog.jenkins
