---
- hosts: jenkins
  gather_facts: yes

  vars:
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_password: admin

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
